version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker exec -it docker101_web_1 bash -c "cd /app; pytest"

workflows:
    "Hello Workflow":
        jobs:
          - build