version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker exec -it web101_test bash -c "cd /app; pytest"

workflows:
    "Hello Workflow":
        jobs:
          - build